use_frameworks!

platform :ios, '8.0'

target 'ZLFBaseConfigTool_Example' do
  pod 'ZLFBaseConfigTool', :path => '../'

  target 'ZLFBaseConfigTool_Tests' do
    inherit! :search_paths

    
  end
end
